# Generated by Django 3.2.4 on 2021-12-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_creator_id'),
        ('notifications', '0002_alter_notification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('created_at', 'updated_at', 'title', 'content')},
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_id', to='users.user'),
        ),
    ]
