# Generated by Django 3.2.4 on 2022-01-25 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_auto_20211231_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=30, verbose_name='currency')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='limit amount')),
                ('borrowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='borrowed amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_id', to='users.user')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ('created_at', 'updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('beneficiary_id',), name='unique_loan'),
        ),
    ]
