# Generated by Django 3.2.4 on 2022-01-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiat_wallets', '0003_fiatwallet_type'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_wallet_id', to='fiat_wallets.fiatwallet'),
        ),
    ]
