version: "3.8"

services:
  bitlipa-api:
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    container_name: bitlipa-api
    command: ./scripts/run.sh
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME

    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/opt/postgres
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 5432:5432
volumes:
  postgres_volume:
