version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "bitlipa"
    restart: unless-stopped
    ports:
      - 5432:5432
  dev:
    container_name: bitlipa-dev-api
    image: ${DOCKER_REGISTRY:-bitlipa}/bitlipa-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "./scripts/run.sh"
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - db

  staging:
    container_name: bitlipa-staging-api
    image: ${DOCKER_REGISTRY:-bitlipa}/bitlipa-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  prod:
    container_name: bitlipa-prod-api
    image: ${DOCKER_REGISTRY:-bitlipa}/bitlipa-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
