# Generated by Django 3.2.4 on 2021-08-15 09:15

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=30, verbose_name='from currency')),
                ('currency', models.CharField(max_length=30, verbose_name='to currency')),
                ('base_amount', djmoney.models.fields.MoneyField(currency_field_name='base_currency', decimal_places=18, default=Decimal('1'), max_digits=36, verbose_name='base_amount')),
                ('rate', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('1'), max_digits=36, verbose_name='exchange rate')),
                ('date', models.CharField(blank=True, max_length=30, null=True, verbose_name='exchange rate date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
            ],
            options={
                'db_table': 'currency_exchange',
                'ordering': ('base_currency', 'currency'),
                'unique_together': {('base_currency', 'currency')},
            },
        ),
    ]
