# Generated by Django 3.2.4 on 2021-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
