apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitlipa-api.fullname" . }}
  labels:
    {{- include "bitlipa-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bitlipa-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitlipa-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitlipa-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "AWS_REGION_NAME"
              valueFrom:
                secretKeyRef:
                  key:  AWS_REGION_NAME
                  name: {{ .Release.Name }}-secrets
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  key:  AWS_ACCESS_KEY
                  name: {{ .Release.Name }}-secrets
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  key:  AWS_SECRET_KEY
                  name: {{ .Release.Name }}-secrets
            - name: "AWS_SECRET_NAME"
              valueFrom:
                secretKeyRef:
                  key:  AWS_SECRET_NAME
                  name: {{ .Release.Name }}-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
