apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  AWS_REGION_NAME: {{ .Values.AWS_REGION_NAME | b64enc }}
  AWS_ACCESS_KEY: {{ .Values.AWS_ACCESS_KEY | b64enc }}
  AWS_SECRET_KEY: {{ .Values.AWS_SECRET_KEY | b64enc }}
  AWS_SECRET_NAME: {{ .Values.AWS_SECRET_NAME | b64enc }}
