# Generated by Django 3.2.4 on 2021-07-03 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('otp', models.CharField(max_length=6, verbose_name='verification code')),
                ('destination', models.CharField(choices=[('SMS', 'Send on SMS'), ('EMAIL', 'Send on email')], default='SMS', max_length=6, verbose_name='destination of the verification code')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'db_table': 'otp',
                'ordering': ('updated_at', 'created_at'),
            },
        ),
    ]
