# Generated by Django 3.2.4 on 2021-10-18 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, max_length=30, null=True, verbose_name='currency')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True, verbose_name='min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='max amount')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('country_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='country code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
            ],
            options={
                'db_table': 'transaction_limits',
                'ordering': ('created_at', 'updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='transactionlimit',
            constraint=models.UniqueConstraint(fields=('currency', 'min_amount', 'max_amount', 'country', 'country_code'), name='unique_transaction_limit'),
        ),
    ]
