# Generated by Django 3.2.4 on 2022-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_limits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlimit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily limit'), ('WEEKLY', 'Weekly limit'), ('MONTHLY', 'Monthly limit')], default='DAILY', max_length=10, verbose_name='frequency'),
        ),
    ]
