# Generated by Django 3.2.4 on 2022-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_limits', '0002_transactionlimit_frequency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionlimit',
            name='unique_transaction_limit',
        ),
        migrations.RemoveField(
            model_name='transactionlimit',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='transactionlimit',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='transactionlimit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True, verbose_name='amount'),
        ),
        migrations.AddConstraint(
            model_name='transactionlimit',
            constraint=models.UniqueConstraint(fields=('currency', 'amount', 'country', 'country_code'), name='unique_transaction_limit'),
        ),
    ]
