# Generated by Django 3.2.4 on 2022-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_limits', '0003_auto_20220413_2037'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionlimit',
            name='unique_transaction_limit',
        ),
        migrations.AddConstraint(
            model_name='transactionlimit',
            constraint=models.UniqueConstraint(fields=('currency', 'amount', 'country', 'country_code', 'frequency'), name='unique_transaction_limit'),
        ),
    ]
