# Generated by Django 3.2.4 on 2021-07-17 21:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet name')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet type')),
                ('wallet_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet ID')),
                ('currency', models.CharField(max_length=30, verbose_name='wallet currency')),
                ('balance', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=19, verbose_name='wallet balance')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='wallet address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='wallet description')),
                ('api_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='wallet API token')),
                ('api_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='wallet API secret')),
                ('api_refresh_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='wallet API refresh token')),
                ('logo_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='wallet logo')),
                ('is_master', models.BooleanField(default=False, verbose_name='is master wallet')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'crypto_wallets',
                'ordering': ('name', 'address', 'currency'),
            },
        ),
    ]
