# Generated by Django 3.2.4 on 2021-07-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptowallet',
            options={'ordering': ('created_at', 'updated_at')},
        ),
    ]
