# Generated by Django 3.2.4 on 2021-07-21 10:52

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0002_alter_cryptowallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='wallet balance'),
        ),
    ]
