# Generated by Django 3.2.4 on 2021-07-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0003_alter_cryptowallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='order_id_prefix',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='order ID preffix'),
        ),
    ]
