# Generated by Django 3.2.4 on 2021-06-14 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('phonenumber', models.CharField(max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('pin', models.TextField(verbose_name='PIN')),
                ('password', models.TextField(null=True, verbose_name='password')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is email verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='is phone verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='deleted at')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('first_name', 'middle_name', 'last_name'),
            },
        ),
    ]
