# Generated by Django 3.2.4 on 2021-06-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_deleted_at'),
        ('users', '0002_user_otp'),
    ]

    operations = [
    ]
