# Generated by Django 3.2.4 on 2021-06-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_alter_user_deleted_at_0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Device id'),
        ),
    ]
