# Generated by Django 3.2.4 on 2021-07-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at', 'created_at')},
        ),
    ]
