# Generated by Django 3.2.4 on 2021-08-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local_currency',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='local currency'),
        ),
    ]
