# Generated by Django 3.2.4 on 2021-09-20 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_local_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Documents'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='is_account_verified',
            field=models.BooleanField(default=False, verbose_name='is account verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_picture_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Selfie'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='status'),
        ),
    ]
