# Generated by Django 3.2.4 on 2021-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210920_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('ID', 'National ID'), ('PASSPORT', 'Passport')], default='ID', max_length=10, verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_of_residence_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proof of residence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID or Passport'),
        ),
    ]
