# Generated by Django 3.2.4 on 2021-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210923_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile picture'),
        ),
    ]
