# Generated by Django 3.2.4 on 2021-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_url',
        ),
        migrations.AddField(
            model_name='user',
            name='document_back_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Back side of ID or Passport'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_front_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Front side of ID or Passport'),
        ),
    ]
