# Generated by Django 3.2.4 on 2021-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210923_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_pin_change_date',
            field=models.DateTimeField(null=True, verbose_name='initial PIN change date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_account_blocked',
            field=models.BooleanField(default=False, verbose_name='is account blocked'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_change_count',
            field=models.IntegerField(default=0, verbose_name='PIN change count'),
        ),
    ]
