# Generated by Django 3.2.4 on 2021-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211001_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_temporary',
            field=models.BooleanField(default=False, verbose_name='is password temporary'),
        ),
    ]
