# Generated by Django 3.2.4 on 2021-10-29 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_password_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
