# Generated by Django 3.2.4 on 2021-12-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_wrong_login_attempt_date',
            field=models.DateTimeField(null=True, verbose_name='last wrong login attempt date'),
        ),
        migrations.AddField(
            model_name='user',
            name='wrong_login_attempts_count',
            field=models.IntegerField(default=0, verbose_name='wrong login attempts count'),
        ),
    ]
