# Generated by Django 3.2.4 on 2021-10-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='tile'),
        ),
    ]
