# Generated by Django 3.2.4 on 2021-07-25 22:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='transaction type')),
                ('wallet_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet ID')),
                ('order_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='order ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='serial number')),
                ('vout_index', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='index of vout')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction ID')),
                ('currency', models.CharField(max_length=30, verbose_name='transaction currency')),
                ('fees', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction fees')),
                ('amount', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction amount')),
                ('total_amount', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction total amount')),
                ('from_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='source crypto wallet address')),
                ('to_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='destination crypto wallet address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='transaction description')),
                ('state', models.CharField(choices=[('1', 'Processing'), ('2', 'TXID in pool'), ('3', 'TXID in chain'), ('5', 'Failed'), ('8', 'Cancelled'), ('10', 'Dropped')], default='Processing', max_length=30, verbose_name='transaction state')),
                ('is_balance_updated', models.BooleanField(default=False, verbose_name='is sender or receiver balance updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_id', to='users.user', verbose_name='receiver')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_id', to='users.user', verbose_name='sender')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ('created_at', 'updated_at'),
            },
        ),
    ]
