# Generated by Django 3.2.4 on 2021-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('0', 'Init'), ('1', 'Processing'), ('2', 'TXID in pool'), ('3', 'TXID in chain'), ('4', 'Done'), ('5', 'Failed'), ('8', 'Cancelled'), ('10', 'Dropped')], default='Processing', max_length=30, verbose_name='transaction state'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='transaction ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vout_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='index of vout'),
        ),
    ]
