# Generated by Django 3.2.4 on 2021-08-30 09:20

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210726_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fees',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction fee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='currency exchange fee'),
        ),
    ]
