# Generated by Django 3.2.4 on 2021-08-30 09:28

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210830_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='source currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_currency',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='target currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='to_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='from_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction fee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fx_fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='to_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='currency exchange fee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='from_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction total amount'),
        ),
    ]
