# Generated by Django 3.2.4 on 2021-11-12 18:01

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210830_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='from_address',
            new_name='source_address',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_currency',
            new_name='source_currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_address',
            new_name='target_address',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_currency',
            new_name='target_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='source_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction source amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_total_amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='source_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction source total amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='target_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction target amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='source_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='transaction fee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fx_fee',
            field=djmoney.models.fields.MoneyField(currency_field_name='target_currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='currency exchange fee'),
        ),
    ]
