# Generated by Django 3.2.4 on 2022-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_fx_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='wallet ID'),
        ),
    ]
