# Generated by Django 3.2.4 on 2021-12-22 01:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_user_creator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet name')),
                ('number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='wallet number')),
                ('currency', models.CharField(blank=True, max_length=30, null=True, verbose_name='wallet currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
                ('balance', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='wallet balance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'fiat_wallets',
                'ordering': ('name', 'currency', 'number'),
            },
        ),
    ]
