# Generated by Django 3.2.4 on 2022-01-03 14:35

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiat_wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='wallet balance'),
        ),
    ]
