# Generated by Django 3.2.4 on 2022-01-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiat_wallets', '0002_alter_fiatwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwallet',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'Personal wallet'), ('LOAN', 'Loan wallet'), ('SAVING', 'Saving wallet')], default='PERSONAL', max_length=10, verbose_name='wallet type'),
        ),
    ]
