# Generated by Django 3.2.4 on 2021-08-29 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('type', models.CharField(choices=[('FLAT', 'Flat fee'), ('PERCENTAGE', 'Percentage fee')], default='FLAT', max_length=10, verbose_name='fee type')),
                ('currency', models.CharField(blank=True, max_length=30, null=True, verbose_name='currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted at')),
            ],
            options={
                'db_table': 'fees',
                'ordering': ('created_at', 'updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_fee'),
        ),
    ]
