# Generated by Django 3.2.4 on 2021-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiat_wallet', '0002_alter_fiatwallet_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwallet',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='wallet number'),
        ),
    ]
