# Generated by Django 3.2.4 on 2021-08-22 16:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_firebase_token'),
        ('fiat_wallet', '0004_auto_20210822_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0'), max_digits=36, verbose_name='wallet balance'),
        ),
        migrations.AddField(
            model_name='fiatwallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
